version: "3.7"
services:
  test:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 28080:8080
  daemon:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro